#!/bin/bash
# =============================================================================
#  rebuild-index.command  —  Dig Deeper study-library index builder
# -----------------------------------------------------------------------------
#  Double-click this file (or run it in Terminal) to (re)build the catalogue
#  pages for your Bible-study library. It:
#
#    1. writes the TOP-LEVEL  index.html  (a portal listing every book that has
#       HTML documents, in canonical Bible order), and
#    2. writes a per-book  index.html  inside any book folder that doesn't
#       already have a hand-made one.
#
#  It NEVER touches your study documents, and it NEVER overwrites a hand-made
#  index (one that lacks the "auto-generated" marker below). So a curated page
#  like the Philippians index is safe; only auto pages are refreshed.
#
#  To preview without writing anything, run:   DRY=1 ./rebuild-index.command
# =============================================================================

LC_ALL=C
ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT" || { echo "Cannot enter $ROOT"; exit 1; }

MARK='<!-- auto-generated by rebuild-index.command -->'

# ----- house-style CSS (shared by every generated page) ----------------------
read -r -d '' CSS <<'CSS_END'
  :root{--ink:#24211c;--muted:#6b6459;--rule:#e3ddd1;--accent:#7a5c2e;--bg:#fbf9f4;
    --card:#fff;--chip:#efe9dc;--chipink:#5a4a2a;--star:#a8791f;}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);
    font-family:"Liberation Serif","Georgia",serif;font-size:18px;line-height:1.5;}
  .page{max-width:980px;margin:0 auto;padding:2.6rem clamp(1rem,4vw,3rem) 5rem;}
  header.masthead{border-bottom:2px solid var(--rule);padding-bottom:1.3rem;margin-bottom:1.6rem;}
  h1{font-size:2.05rem;line-height:1.1;margin:0 0 .35rem;}
  .subtitle{color:var(--muted);font-size:1.02rem;margin:.2rem 0 0;}
  .meta{color:var(--muted);font-size:.85rem;margin-top:.9rem;letter-spacing:.02em;}
  h2.section{font-size:1.1rem;letter-spacing:.06em;text-transform:uppercase;color:var(--accent);
    margin:2.3rem 0 .3rem;padding-top:1rem;border-top:1px solid var(--rule);}
  .section-note{color:var(--muted);font-size:.92rem;margin:.1rem 0 1.1rem;}
  .grid{display:grid;grid-template-columns:1fr;gap:.85rem;}
  @media(min-width:640px){.grid.two{grid-template-columns:1fr 1fr;}
    .grid.three{grid-template-columns:1fr 1fr 1fr;}}
  .card{display:block;background:var(--card);border:1px solid var(--rule);border-radius:8px;
    padding:1rem 1.15rem;text-decoration:none;color:var(--ink);
    transition:border-color .15s ease,box-shadow .15s ease,transform .05s ease;}
  .card:hover{border-color:var(--accent);box-shadow:0 2px 10px rgba(122,92,46,.10);}
  .card:active{transform:translateY(1px);}
  .card .ref{display:inline-block;font-family:"Liberation Mono",ui-monospace,monospace;
    font-size:.78rem;background:var(--chip);color:var(--chipink);
    padding:.12em .5em;border-radius:4px;margin-bottom:.45rem;letter-spacing:.02em;}
  .card .ref.big{background:var(--accent);color:#fff;}
  .card h3{font-size:1.1rem;margin:.15rem 0 .3rem;line-height:1.2;color:var(--accent);}
  .card p{margin:.2rem 0 0;font-size:.93rem;color:#40392e;}
  .card .foot{margin-top:.6rem;font-size:.8rem;color:var(--muted);}
  .star{color:var(--star);font-weight:bold;}
  .lead .card{border-left:4px solid var(--accent);}
  footer{margin-top:3rem;padding-top:1.2rem;border-top:1px solid var(--rule);
    color:var(--muted);font-size:.85rem;line-height:1.55;}
  footer code{background:var(--chip);padding:.05em .35em;border-radius:3px;font-size:.85em;}
CSS_END

# ----- helpers ---------------------------------------------------------------

# lowercase + keep only a-z0-9 (for matching folder/file names loosely)
norm() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]'; }

# pull the <title> text out of an HTML file (fallback: the file name)
html_title() {
  local t
  t="$(grep -o '<title>[^<]*</title>' "$1" 2>/dev/null | head -1 \
        | sed -e 's/<title>//' -e 's#</title>##')"
  [ -n "$t" ] && printf '%s' "$t" || basename "$1" .html
}

# canonical order rank (1..66) for a normalised book-folder name; 999 if unknown
#   Old Testament (1..39): HEBREW CANON order — Torah, Prophets, Writings
#     (Writings run: Psalms, Proverbs, Job, Song, Ruth, Lamentations, Ecclesiastes,
#      Esther, Daniel, Ezra-Nehemiah, Chronicles).
#   New Testament (40..66): modern English order (Gospels, Acts, Paul, Hebrews, others).
rank_of() {
  case "$1" in
    # --- Torah ---
    torah|pentateuch|thetorah) echo 0;;
    genesis) echo 1;; exodus) echo 2;; leviticus) echo 3;; numbers) echo 4;;
    deuteronomy) echo 5;;
    # --- Prophets ---
    joshua) echo 6;; judges) echo 7;;
    1samuel) echo 8;; booksofsamuel|samuel) echo 8;; 2samuel) echo 9;;
    1kings) echo 10;; booksofkings|kings) echo 10;; 2kings) echo 11;;
    isaiah) echo 12;; jeremiah) echo 13;; ezekiel) echo 14;;
    thetwelve|thebookofthetwelve|booksofthetwelve|minorprophets|hosea) echo 15;;
    joel) echo 16;; amos) echo 17;; obadiah) echo 18;; jonah) echo 19;; micah) echo 20;;
    nahum) echo 21;; habakkuk) echo 22;; zephaniah) echo 23;; haggai) echo 24;;
    zechariah) echo 25;; malachi) echo 26;;
    # --- Writings (Hagiographa) ---
    psalms|psalm) echo 27;; proverbs) echo 28;; job) echo 29;;
    songofsongs|songofsolomon|canticles|song) echo 30;;
    ruth) echo 31;; lamentations) echo 32;; ecclesiastes) echo 33;; esther) echo 34;;
    daniel) echo 35;;
    ezra|ezranehemiah|ezraandnehemiah) echo 36;; nehemiah) echo 37;;
    1chronicles) echo 38;; booksofchronicles|chronicles) echo 38;; 2chronicles) echo 39;;
    # --- New Testament (modern English order) ---
    matthew) echo 40;; mark) echo 41;; luke) echo 42;; john) echo 43;; acts) echo 44;;
    romans) echo 45;; 1corinthians) echo 46;; 2corinthians) echo 47;; galatians) echo 48;;
    ephesians) echo 49;; philippians) echo 50;; colossians) echo 51;;
    1thessalonians) echo 52;; 2thessalonians) echo 53;; 1timothy) echo 54;;
    2timothy) echo 55;; titus) echo 56;; philemon) echo 57;; hebrews) echo 58;;
    james) echo 59;; 1peter) echo 60;; 2peter) echo 61;;
    1john) echo 62;; 23john|johnepistles) echo 63;; 2john) echo 63;; 3john) echo 64;;
    jude) echo 65;; revelation) echo 66;;
    *) echo 999;;
  esac
}

# collection detection: a folder is a "collection" if it holds one or more
# immediate subfolders that are themselves canonical books (rank < 999).
# This catches Torah (Genesis..Deuteronomy) and The Twelve (Hosea..Malachi),
# while leaving a normal book with an auxiliary subfolder (e.g. Acts/_sources) alone.
is_collection() {
  local d="$1" sub sn
  for sub in "$d"/*/; do
    [ -d "$sub" ] || continue
    sn="$(basename "$sub")"
    case "$sn" in _*|.*) continue;; esac
    [ "$(rank_of "$(norm "$sn")")" -ne 999 ] && return 0
  done
  return 1
}

# count the member books (canonical subfolders) of a collection
count_members() {
  local d="$1" sub sn c=0
  for sub in "$d"/*/; do
    [ -d "$sub" ] || continue
    sn="$(basename "$sub")"
    case "$sn" in _*|.*) continue;; esac
    [ "$(rank_of "$(norm "$sn")")" -ne 999 ] && c=$((c+1))
  done
  echo "$c"
}

# classify one html file by its base name -> sort-group + type label + chip class
# echoes: "<group> <typelabel>" ; group 1=overview 2=synthesis 3=sweep 4=sermon
#         5=passage 6=other
classify() {
  local b; b="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')"
  case "$b" in
    *overview*)         echo "1 Book Overview|big";;
    *macro-synthesis*|*macrosynthesis*) echo "2 Macro-Synthesis|big";;
    *orientation*)      echo "1 Orientation Frame|big";;
    *whole-book*|*wholebook*|*book-sweep*) echo "3 Whole-Book Sweep|";;
    *sweep*)            echo "3 Whole-Letter Sweep|";;
    *point-purpose*|*sermon*) echo "4 Sermon Plan|";;
    *) echo "5 Study|";; # provisional; passage detection happens in build_book
  esac
}

# ----- passage-reference parser ----------------------------------------------
# Reads a file stem and echoes "<sortkey>|<display>" if it ends in a recognised
# passage suffix; echoes nothing otherwise. Handles, longest form first:
#   -C-VtoC-V   cross-chapter range   e.g. -12-1to13-16  -> 12:1–13:16
#   -C-VtoV     within-chapter range  e.g. -19-1to25     -> 19:1–25
#   -C-V        single verse          e.g. -3-16         -> 3:16
#   -CtoC       chapter range         e.g. -3to5         -> Ch. 3–5
#   -C          whole chapter         e.g. -6            -> Ch. 6
NDASH='–'
num() { printf '%s' "$((10#$1))"; }   # strip leading zeros safely

passage_ref() {
  local s="$1" c1 v1 c2 v2
  s="${s%.house}"                      # tolerate .house.html variants
  if [[ "$s" =~ -([0-9]+)-([0-9]+)to([0-9]+)-([0-9]+)$ ]]; then
    c1=$(num "${BASH_REMATCH[1]}"); v1=$(num "${BASH_REMATCH[2]}")
    c2=$(num "${BASH_REMATCH[3]}"); v2=$(num "${BASH_REMATCH[4]}")
    printf '%03d%05d|%s' "$c1" "$v1" "$c1:$v1$NDASH$c2:$v2"
  elif [[ "$s" =~ -([0-9]+)-([0-9]+)to([0-9]+)$ ]]; then
    c1=$(num "${BASH_REMATCH[1]}"); v1=$(num "${BASH_REMATCH[2]}"); v2=$(num "${BASH_REMATCH[3]}")
    printf '%03d%05d|%s' "$c1" "$v1" "$c1:$v1$NDASH$v2"
  elif [[ "$s" =~ -([0-9]+)-([0-9]+)$ ]]; then
    c1=$(num "${BASH_REMATCH[1]}"); v1=$(num "${BASH_REMATCH[2]}")
    printf '%03d%05d|%s' "$c1" "$v1" "$c1:$v1"
  elif [[ "$s" =~ -([0-9]+)to([0-9]+)$ ]]; then
    c1=$(num "${BASH_REMATCH[1]}"); c2=$(num "${BASH_REMATCH[2]}")
    printf '%03d%05d|%s' "$c1" 0 "Ch. $c1$NDASH$c2"
  elif [[ "$s" =~ -([0-9]+)$ ]]; then
    c1=$(num "${BASH_REMATCH[1]}")
    printf '%03d%05d|%s' "$c1" 0 "Ch. $c1"
  fi
}

# write a file unless DRY is set; obeys curated-protection for per-book indexes
write_page() { # $1 outfile  $2 content
  if [ -n "${DRY:-}" ]; then
    echo "   [dry-run] would write: $1"
  else
    printf '%s\n' "$2" > "$1"
    echo "   wrote: $1"
  fi
}

page_shell() { # $1 title  $2 body-html  -> full HTML document on stdout
  cat <<EOF
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$1</title>
$MARK
<style>
$CSS
</style>
</head>
<body>
<div class="page">
$2
</div>
</body>
</html>
EOF
}

# ----- build one book's index.html -------------------------------------------
build_book_index() { # $1 = book folder name
  local dir="$1" idx="$1/index.html"
  # protection: skip a hand-made index (present, but without our marker)
  if [ -f "$idx" ] && ! grep -qF "$MARK" "$idx"; then
    echo " · $dir: keeping hand-made index.html (not overwritten)"
    return 0
  fi

  local back_href="${2:-../index.html}" back_label="${3:-Study Library}"
  local body head_docs="" passage_lines="" other_docs="" f base low grp label chip title pr disp key
  head_docs=""; passage_lines=""; other_docs=""
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    base="$(basename "$f")"; low="$(printf '%s' "$base" | tr '[:upper:]' '[:lower:]')"
    title="$(html_title "$f")"
    # named document types (overview / synthesis / sweep / sermon plan) win first;
    # anything left over is tested for a passage reference in its file name.
    read grp rest <<<"$(classify "$base")"
    label="${rest%%|*}"; chip="${rest#*|}"
    pr=""
    [ "$grp" = "5" ] && pr="$(passage_ref "${base%.html}")"
    if [ -n "$pr" ]; then
      key="${pr%%|*}"; disp="${pr#*|}"
      passage_lines="${passage_lines}${key}|${disp}|${base}|${title}"$'\n'
    else
      local c; c="$(printf '<a class="card" href="%s"><span class="ref %s">%s</span><h3>%s</h3></a>\n' \
                    "$base" "$chip" "$label" "$title")"
      case "$grp" in
        1|2|3|4) head_docs="${head_docs}${grp}\t${c}"$'\n';;
        *) other_docs="${other_docs}${c}";;
      esac
    fi
  done <<< "$(find "$dir" -maxdepth 1 -name '*.html' ! -name 'index.html' 2>/dev/null | sort)"

  # orientation cards, ordered overview→synthesis→sweep→sermon
  local orient=""
  orient="$(printf '%b' "$head_docs" | sort | sed 's/^[0-9]\t//')"

  # passage cards, canonical order
  local passages=""
  if [ -n "$passage_lines" ]; then
    passages="$(printf '%s' "$passage_lines" | sort | while IFS='|' read -r k disp b t; do
        [ -n "$b" ] || continue
        printf '<a class="card" href="%s"><span class="ref">%s</span><h3>%s</h3></a>\n' "$b" "$disp" "$t"
      done)"
  fi

  body="<header class=\"masthead\"><h1>$dir</h1>"
  body="$body<p class=\"subtitle\">Dig Deeper study documents for $dir. Each card opens an HTML report; the same studies also exist as .odt and .md alongside.</p>"
  body="$body<p class=\"meta\"><a href=\"$back_href\" style=\"color:var(--accent)\">&larr; $back_label</a></p></header>"
  if [ -n "$orient" ]; then
    body="$body<h2 class=\"section\">Orientation</h2><div class=\"grid two lead\">$orient</div>"
  fi
  if [ -n "$passages" ]; then
    body="$body<h2 class=\"section\">Passage studies</h2><div class=\"grid two\">$passages</div>"
  fi
  if [ -n "$other_docs" ]; then
    body="$body<h2 class=\"section\">Other documents</h2><div class=\"grid two\">$other_docs</div>"
  fi
  body="$body<footer><p>Auto-generated by <code>rebuild-index.command</code>. To give this book a richer, hand-written page, replace this file and it will be left alone from then on.</p></footer>"

  write_page "$idx" "$(page_shell "$dir — Study Library" "$body")"
}

# ----- build a collection's index.html (e.g. Torah, The Twelve) --------------
# A collection page lists the collection's OWN documents (overviews, syntheses)
# plus one card per member book, and (re)builds each member book's own index
# with a back-link to the collection.
build_collection_index() { # $1 = collection folder name
  local dir="$1" idx="$1/index.html" protected=""
  if [ -f "$idx" ] && ! grep -qF "$MARK" "$idx"; then
    protected="yes"
    echo " · $dir: keeping hand-made collection index.html (not overwritten)"
  fi

  # (a) the collection's own top-level documents (overview / synthesis / etc.)
  local own="" f base title grp rest label chip c
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    base="$(basename "$f")"; title="$(html_title "$f")"
    read grp rest <<<"$(classify "$base")"
    label="${rest%%|*}"; chip="${rest#*|}"
    c="$(printf '<a class="card" href="%s"><span class="ref %s">%s</span><h3>%s</h3></a>\n' \
          "$base" "$chip" "$label" "$title")"
    own="${own}${c}"
  done <<< "$(find "$dir" -maxdepth 1 -name '*.html' ! -name 'index.html' 2>/dev/null | sort)"

  # (b) member books, in canonical order; build each one's own index too
  local rows="" sub sn r n
  for sub in "$dir"/*/; do
    sub="${sub%/}"; sn="$(basename "$sub")"
    case "$sn" in _*|.*) continue;; esac
    r=$(rank_of "$(norm "$sn")")
    [ "$r" -eq 999 ] && continue
    n=$(find "$sub" -maxdepth 1 -name '*.html' ! -name 'index.html' 2>/dev/null | wc -l | tr -d ' ')
    rows="${rows}$(printf '%03d\t%s\t%s' "$r" "$sn" "$n")"$'\n'
    build_book_index "$sub" "../index.html" "$dir"
  done
  local members=""
  members="$(printf '%b' "$rows" | grep -v '^$' | sort -n | while IFS=$'\t' read -r rr nm cnt; do
      [ -n "$nm" ] || continue
      pl="documents"; [ "$cnt" -eq 1 ] && pl="document"
      printf '<a class="card" href="%s/index.html"><span class="ref">%s %s</span><h3>%s</h3></a>\n' \
        "$nm" "$cnt" "$pl" "$nm"
    done)"

  [ -n "$protected" ] && return 0

  local body
  body="<header class=\"masthead\"><h1>$dir</h1>"
  body="$body<p class=\"subtitle\">A collection: whole-of-$dir studies, plus a page for each book within it. Every HTML study also exists as .odt and .md alongside it.</p>"
  body="$body<p class=\"meta\"><a href=\"../index.html\" style=\"color:var(--accent)\">&larr; Study Library</a></p></header>"
  [ -n "$own" ]     && body="$body<h2 class=\"section\">$dir — overview &amp; synthesis</h2><div class=\"grid two lead\">$own</div>"
  [ -n "$members" ] && body="$body<h2 class=\"section\">Books</h2><div class=\"grid three\">$members</div>"
  body="$body<footer><p>Auto-generated by <code>rebuild-index.command</code>. This is a collection page; each book nested inside <code>$dir/</code> keeps its own page and links back here.</p></footer>"
  write_page "$idx" "$(page_shell "$dir — Study Library" "$body")"
}

# ----- gather books & build ---------------------------------------------------
echo "Rebuilding library indexes in: $ROOT"
[ -n "${DRY:-}" ] && echo "(DRY RUN — nothing will be written)"
echo

book_rows=""      # rank \t folder \t count   (books that HAVE html docs)
pending=""        # folders with material but no html yet

for d in */; do
  d="${d%/}"
  [ -d "$d" ] || continue
  case "$d" in .*) continue;; esac
  # collection folder (holds canonical-book subfolders)? build its page + members
  if is_collection "$d"; then
    build_collection_index "$d"
    r=$(rank_of "$(norm "$d")")
    book_rows="${book_rows}${r}\t${d}\t$(count_members "$d")\tcollection"$'\n'
    continue
  fi
  n=$(find "$d" -maxdepth 1 -name '*.html' ! -name 'index.html' 2>/dev/null | wc -l | tr -d ' ')
  if [ "$n" -eq 0 ]; then
    # has other material (md/odt) but no html yet?
    m=$(find "$d" -maxdepth 1 \( -name '*.md' -o -name '*.odt' \) 2>/dev/null | wc -l | tr -d ' ')
    [ "$m" -gt 0 ] && pending="${pending}${d}, "
    continue
  fi
  r=$(rank_of "$(norm "$d")")
  book_rows="${book_rows}${r}\t${d}\t${n}\tbook"$'\n'
  build_book_index "$d"
done

# ----- top-level portal -------------------------------------------------------
sorted="$(printf '%b' "$book_rows" | grep -v '^$' | sort -n -k1,1 -t$'\t')"

emit_cards() { # $1 = testament predicate: OT | NT | OTHER
  printf '%s\n' "$sorted" | while IFS=$'\t' read -r r d n k; do
    [ -n "$d" ] || continue
    case "$1" in
      OT)    [ "$r" -le 39 ] || continue;;
      NT)    { [ "$r" -ge 40 ] && [ "$r" -le 66 ]; } || continue;;
      OTHER) [ "$r" -ge 900 ] || continue;;
    esac
    if [ "$k" = "collection" ]; then
      plural="books"; [ "$n" -eq 1 ] && plural="book"
    else
      plural="documents"; [ "$n" -eq 1 ] && plural="document"
    fi
    printf '<a class="card" href="%s/index.html"><span class="ref">%s %s</span><h3>%s</h3></a>\n' \
      "$d" "$n" "$plural" "$d"
  done
}

ot_cards="$(emit_cards OT)"
nt_cards="$(emit_cards NT)"
other_cards="$(emit_cards OTHER)"
bookcount="$(printf '%s\n' "$sorted" | grep -c $'\t')"
today="$(date '+%e %B %Y' | sed 's/^ *//')"

pbody="<header class=\"masthead\"><h1>Dig Deeper — Study Library</h1>"
pbody="$pbody<p class=\"subtitle\">A growing library of Bible-study material: whole-book overviews, cross-passage syntheses, and passage-by-passage exegetical reports.</p>"
pbody="$pbody<p class=\"meta\">Local catalogue &middot; ${bookcount} book(s) with HTML &middot; rebuilt ${today}</p></header>"

if [ -f "preaching-toolkit-guide.html" ]; then
  pbody="$pbody<div class=\"grid lead\"><a class=\"card\" href=\"preaching-toolkit-guide.html\"><span class=\"ref big\">Guide</span><h3>About the Preaching Toolkit</h3><p>How the overviews, sweeps, digs and syntheses fit together.</p></a></div>"
fi

[ -n "$ot_cards" ]    && pbody="$pbody<h2 class=\"section\">Old Testament</h2><div class=\"grid three\">$ot_cards</div>"
[ -n "$nt_cards" ]    && pbody="$pbody<h2 class=\"section\">New Testament</h2><div class=\"grid three\">$nt_cards</div>"
[ -n "$other_cards" ] && pbody="$pbody<h2 class=\"section\">Other</h2><div class=\"grid three\">$other_cards</div>"

pfoot="<footer><p>This is a local index. Every link is a file in this folder tree, so the whole library works offline &mdash; just open <code>index.html</code> and click through. Nothing is published online.</p>"
if [ -n "$pending" ]; then
  pfoot="$pfoot<p>Also in the library, not yet rendered to HTML: ${pending%, }.</p>"
fi
pfoot="$pfoot<p>To refresh this catalogue after adding material, double-click <code>rebuild-index.command</code>. Hand-made book pages are never overwritten.</p></footer>"
pbody="$pbody$pfoot"

write_page "index.html" "$(page_shell "Dig Deeper — Study Library" "$pbody")"

echo
echo "Done. Open  index.html  in your browser."
exit 0
