<#
=============================================================================
  rebuild-index.ps1  -  Dig Deeper study-library index builder (Windows)
-----------------------------------------------------------------------------
  Windows PowerShell port of rebuild-index.command. Run it (or double-click
  rebuild-index.bat, which launches this) to (re)build the catalogue pages for
  your Bible-study library. It:

    1. writes the TOP-LEVEL  index.html  (a portal listing every book that has
       HTML documents, in canonical Bible order), and
    2. writes a per-book  index.html  inside any book folder that doesn't
       already have a hand-made one.

  It NEVER touches your study documents, and it NEVER overwrites a hand-made
  index (one that lacks the "auto-generated" marker below). So a curated page
  like the Philippians index is safe; only auto pages are refreshed.

  To preview without writing anything, run:   .\rebuild-index.ps1 -Dry
  (or set the DRY environment variable to any value).
=============================================================================
#>

[CmdletBinding()]
param(
    [switch]$Dry
)

$ErrorActionPreference = 'Stop'
if ($env:DRY) { $Dry = $true }

# ROOT = the folder this script lives in
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location -LiteralPath $Root

$Mark = '<!-- auto-generated by rebuild-index.command -->'

# ----- house-style CSS (shared by every generated page) ----------------------
# Kept byte-for-byte identical to the macOS script's output.
$Css = @'
:root{--ink:#24211c;--muted:#6b6459;--rule:#e3ddd1;--accent:#7a5c2e;--bg:#fbf9f4;
    --card:#fff;--chip:#efe9dc;--chipink:#5a4a2a;--star:#a8791f;}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);
    font-family:"Liberation Serif","Georgia",serif;font-size:18px;line-height:1.5;}
  .page{max-width:980px;margin:0 auto;padding:2.6rem clamp(1rem,4vw,3rem) 5rem;}
  header.masthead{border-bottom:2px solid var(--rule);padding-bottom:1.3rem;margin-bottom:1.6rem;}
  h1{font-size:2.05rem;line-height:1.1;margin:0 0 .35rem;}
  .subtitle{color:var(--muted);font-size:1.02rem;margin:.2rem 0 0;}
  .meta{color:var(--muted);font-size:.85rem;margin-top:.9rem;letter-spacing:.02em;}
  h2.section{font-size:1.1rem;letter-spacing:.06em;text-transform:uppercase;color:var(--accent);
    margin:2.3rem 0 .3rem;padding-top:1rem;border-top:1px solid var(--rule);}
  .section-note{color:var(--muted);font-size:.92rem;margin:.1rem 0 1.1rem;}
  .grid{display:grid;grid-template-columns:1fr;gap:.85rem;}
  @media(min-width:640px){.grid.two{grid-template-columns:1fr 1fr;}
    .grid.three{grid-template-columns:1fr 1fr 1fr;}}
  .card{display:block;background:var(--card);border:1px solid var(--rule);border-radius:8px;
    padding:1rem 1.15rem;text-decoration:none;color:var(--ink);
    transition:border-color .15s ease,box-shadow .15s ease,transform .05s ease;}
  .card:hover{border-color:var(--accent);box-shadow:0 2px 10px rgba(122,92,46,.10);}
  .card:active{transform:translateY(1px);}
  .card .ref{display:inline-block;font-family:"Liberation Mono",ui-monospace,monospace;
    font-size:.78rem;background:var(--chip);color:var(--chipink);
    padding:.12em .5em;border-radius:4px;margin-bottom:.45rem;letter-spacing:.02em;}
  .card .ref.big{background:var(--accent);color:#fff;}
  .card h3{font-size:1.1rem;margin:.15rem 0 .3rem;line-height:1.2;color:var(--accent);}
  .card p{margin:.2rem 0 0;font-size:.93rem;color:#40392e;}
  .card .foot{margin-top:.6rem;font-size:.8rem;color:var(--muted);}
  .star{color:var(--star);font-weight:bold;}
  .lead .card{border-left:4px solid var(--accent);}
  footer{margin-top:3rem;padding-top:1.2rem;border-top:1px solid var(--rule);
    color:var(--muted);font-size:.85rem;line-height:1.55;}
  footer code{background:var(--chip);padding:.05em .35em;border-radius:3px;font-size:.85em;}
'@

# ----- helpers ---------------------------------------------------------------

# lowercase + keep only a-z0-9 (for matching folder/file names loosely)
function Get-Norm([string]$s) {
    return ([regex]::Replace($s.ToLowerInvariant(), '[^a-z0-9]', ''))
}

# translate a forward-slash relative path into a full filesystem path
function Get-FsPath([string]$rel) {
    return (Join-Path $Root ($rel -replace '/', [IO.Path]::DirectorySeparatorChar))
}

# pull the <title> text out of an HTML file (fallback: the file name)
function Get-HtmlTitle([string]$path) {
    try {
        $content = [IO.File]::ReadAllText($path)
        $m = [regex]::Match($content, '<title>([^<]*)</title>')
        if ($m.Success -and $m.Groups[1].Value.Trim()) {
            return $m.Groups[1].Value.Trim()
        }
    } catch { }
    return [IO.Path]::GetFileNameWithoutExtension($path)
}

# canonical order rank (1..66) for a normalised book-folder name; 999 if unknown
$RankMap = @{
    'torah'=0;'pentateuch'=0;'thetorah'=0
    'genesis'=1;'exodus'=2;'leviticus'=3;'numbers'=4;'deuteronomy'=5
    'joshua'=6;'judges'=7
    '1samuel'=8;'booksofsamuel'=8;'samuel'=8;'2samuel'=9
    '1kings'=10;'booksofkings'=10;'kings'=10;'2kings'=11
    'isaiah'=12;'jeremiah'=13;'ezekiel'=14
    'thetwelve'=15;'thebookofthetwelve'=15;'booksofthetwelve'=15;'minorprophets'=15;'hosea'=15
    'joel'=16;'amos'=17;'obadiah'=18;'jonah'=19;'micah'=20
    'nahum'=21;'habakkuk'=22;'zephaniah'=23;'haggai'=24
    'zechariah'=25;'malachi'=26
    'psalms'=27;'psalm'=27;'proverbs'=28;'job'=29
    'songofsongs'=30;'songofsolomon'=30;'canticles'=30;'song'=30
    'ruth'=31;'lamentations'=32;'ecclesiastes'=33;'esther'=34
    'daniel'=35
    'ezra'=36;'ezranehemiah'=36;'ezraandnehemiah'=36;'nehemiah'=37
    '1chronicles'=38;'booksofchronicles'=38;'chronicles'=38;'2chronicles'=39
    'matthew'=40;'mark'=41;'luke'=42;'john'=43;'acts'=44
    'romans'=45;'1corinthians'=46;'2corinthians'=47;'galatians'=48
    'ephesians'=49;'philippians'=50;'colossians'=51
    '1thessalonians'=52;'2thessalonians'=53;'1timothy'=54
    '2timothy'=55;'titus'=56;'philemon'=57;'hebrews'=58
    'james'=59;'1peter'=60;'2peter'=61
    '1john'=62;'23john'=63;'johnepistles'=63;'2john'=63;'3john'=64
    'jude'=65;'revelation'=66
}
function Get-Rank([string]$n) {
    if ($RankMap.ContainsKey($n)) { return [int]$RankMap[$n] }
    return 999
}

# immediate canonical-book subfolders of a directory (rel path, forward slash)
function Get-MemberSubdirs([string]$relDir) {
    $full = Get-FsPath $relDir
    $subs = Get-ChildItem -LiteralPath $full -Directory -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -notlike '_*' -and $_.Name -notlike '.*' -and (Get-Rank (Get-Norm $_.Name)) -ne 999 }
    return @($subs)
}

# a folder is a "collection" if it holds >=1 immediate canonical-book subfolder
function Test-Collection([string]$relDir) {
    return ((Get-MemberSubdirs $relDir).Count -gt 0)
}

# count HTML docs (excluding index.html) directly inside a dir
function Get-HtmlCount([string]$relDir) {
    $full = Get-FsPath $relDir
    $files = Get-ChildItem -LiteralPath $full -Filter *.html -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -ne 'index.html' }
    return @($files).Count
}

# ordinal (LC_ALL=C) name sort of a set of FileSystemInfo objects
# Sort-Object's string comparison is culture-aware even with -CaseSensitive
# (e.g. it can order "dig-...html" before "Ezekiel-...html"), which would
# disagree with bash's byte-value LC_ALL=C sort. Use a true ordinal compare.
function Sort-Ordinal($items) {
    $arr = @($items)
    [Array]::Sort($arr, [Comparison[object]]{ param($a, $b) [string]::CompareOrdinal($a.Name, $b.Name) })
    return $arr
}

# classify one html file by its base name -> @(group, label, chip)
#   group 1=overview 2=synthesis 3=sweep 4=sermon 5=other
function Get-Classify([string]$name) {
    $b = $name.ToLowerInvariant()
    if     ($b -like '*overview*')                                    { return @(1, 'Book Overview', 'big') }
    elseif ($b -like '*macro-synthesis*' -or $b -like '*macrosynthesis*') { return @(2, 'Macro-Synthesis', 'big') }
    elseif ($b -like '*sweep*')                                       { return @(3, 'Whole-Letter Sweep', '') }
    elseif ($b -like '*point-purpose*' -or $b -like '*sermon*')       { return @(4, 'Sermon Plan', '') }
    else                                                              { return @(5, '. ', '') }
}

# write a file unless -Dry; UTF-8 (no BOM), LF newlines, single trailing newline
function Write-Page([string]$relOut, [string]$content) {
    if ($Dry) {
        Write-Host "   [dry-run] would write: $relOut"
    } else {
        $content = ($content -replace "`r`n", "`n")
        $utf8 = New-Object System.Text.UTF8Encoding($false)
        [IO.File]::WriteAllText((Get-FsPath $relOut), $content + "`n", $utf8)
        Write-Host "   wrote: $relOut"
    }
}

# full HTML document (title, body) -> string
function Get-PageShell([string]$title, [string]$body) {
    return @"
<!DOCTYPE html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$title</title>
$Mark
<style>
$Css
</style>
</head>
<body>
<div class="page">
$body
</div>
</body>
</html>
"@
}

# ----- build one book's index.html -------------------------------------------
function Build-BookIndex([string]$dir, [string]$backHref = '../index.html', [string]$backLabel = 'Study Library') {
    $idx = "$dir/index.html"
    $idxFull = Get-FsPath $idx
    if ((Test-Path -LiteralPath $idxFull) -and -not (Select-String -LiteralPath $idxFull -SimpleMatch $Mark -Quiet)) {
        Write-Host " $([char]0x00B7) ${dir}: keeping hand-made index.html (not overwritten)"
        return
    }

    $headDocs = New-Object System.Collections.ArrayList
    $passageRows = New-Object System.Collections.ArrayList
    $otherDocs = New-Object System.Collections.ArrayList

    $files = Sort-Ordinal (Get-ChildItem -LiteralPath (Get-FsPath $dir) -Filter *.html -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -ne 'index.html' })

    foreach ($f in $files) {
        $base = $f.Name
        $title = Get-HtmlTitle $f.FullName
        $stem = [IO.Path]::GetFileNameWithoutExtension($base)
        $pm = [regex]::Match($stem, '-([0-9]+)-([0-9]+)(?:to([0-9]+))?$')
        if ($pm.Success) {
            $ch = $pm.Groups[1].Value
            $v1 = $pm.Groups[2].Value
            if ($pm.Groups[3].Success) {
                $disp = "$ch`:$v1" + [char]0x2013 + $pm.Groups[3].Value
            } else {
                $disp = "$ch`:$v1"
            }
            $key = '{0:D3}{1:D5}' -f [int]$ch, [int]$v1
            [void]$passageRows.Add([pscustomobject]@{ Key = $key; Disp = $disp; Base = $base; Title = $title })
        } else {
            $cls = Get-Classify $base
            $grp = [int]$cls[0]; $label = $cls[1]; $chip = $cls[2]
            $card = '<a class="card" href="{0}"><span class="ref {1}">{2}</span><h3>{3}</h3></a>' -f $base, $chip, $label, $title
            if ($grp -ge 1 -and $grp -le 4) {
                [void]$headDocs.Add([pscustomobject]@{ Grp = $grp; Card = $card })
            } else {
                [void]$otherDocs.Add($card)
            }
        }
    }

    $orient = (($headDocs | Sort-Object Grp, Card | ForEach-Object { $_.Card }) -join "`n")
    $passages = (($passageRows | Sort-Object Key | ForEach-Object {
        '<a class="card" href="{0}"><span class="ref">{1}</span><h3>{2}</h3></a>' -f $_.Base, $_.Disp, $_.Title
    }) -join "`n")
    $other = ($otherDocs -join '')

    $body = '<header class="masthead"><h1>{0}</h1>' -f $dir
    $body += '<p class="subtitle">Dig Deeper study documents for {0}. Each card opens an HTML report; the same studies also exist as .odt and .md alongside.</p>' -f $dir
    $body += '<p class="meta"><a href="{0}" style="color:var(--accent)">&larr; {1}</a></p></header>' -f $backHref, $backLabel
    if ($orient)   { $body += '<h2 class="section">Orientation</h2><div class="grid two lead">{0}</div>' -f $orient }
    if ($passages) { $body += '<h2 class="section">Passage studies</h2><div class="grid two">{0}</div>' -f $passages }
    if ($other)    { $body += '<h2 class="section">Other documents</h2><div class="grid two">{0}</div>' -f $other }
    $body += '<footer><p>Auto-generated by <code>rebuild-index.command</code>. To give this book a richer, hand-written page, replace this file and it will be left alone from then on.</p></footer>'

    Write-Page $idx (Get-PageShell ("$dir " + [char]0x2014 + " Study Library") $body)
}

# ----- build a collection's index.html (e.g. Torah, The Twelve) --------------
function Build-CollectionIndex([string]$dir) {
    $idx = "$dir/index.html"
    $idxFull = Get-FsPath $idx
    $protected = $false
    if ((Test-Path -LiteralPath $idxFull) -and -not (Select-String -LiteralPath $idxFull -SimpleMatch $Mark -Quiet)) {
        $protected = $true
        Write-Host " $([char]0x00B7) ${dir}: keeping hand-made collection index.html (not overwritten)"
    }

    # (a) the collection's own top-level documents (overview / synthesis / etc.)
    $ownParts = New-Object System.Collections.ArrayList
    $files = Sort-Ordinal (Get-ChildItem -LiteralPath (Get-FsPath $dir) -Filter *.html -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -ne 'index.html' })
    foreach ($f in $files) {
        $base = $f.Name
        $title = Get-HtmlTitle $f.FullName
        $cls = Get-Classify $base
        $label = $cls[1]; $chip = $cls[2]
        $ownParts.Add(('<a class="card" href="{0}"><span class="ref {1}">{2}</span><h3>{3}</h3></a>' -f $base, $chip, $label, $title)) | Out-Null
    }
    $own = ($ownParts -join '')

    # (b) member books, in canonical order; build each one's own index too
    $rows = New-Object System.Collections.ArrayList
    foreach ($sub in (Get-ChildItem -LiteralPath (Get-FsPath $dir) -Directory -ErrorAction SilentlyContinue)) {
        $sn = $sub.Name
        if ($sn -like '_*' -or $sn -like '.*') { continue }
        $r = Get-Rank (Get-Norm $sn)
        if ($r -eq 999) { continue }
        $rel = "$dir/$sn"
        $n = Get-HtmlCount $rel
        [void]$rows.Add([pscustomobject]@{ Rank = $r; Name = $sn; Count = $n })
        Build-BookIndex $rel '../index.html' $dir
    }
    $members = (($rows | Sort-Object Rank | ForEach-Object {
        $pl = if ($_.Count -eq 1) { 'document' } else { 'documents' }
        '<a class="card" href="{0}/index.html"><span class="ref">{1} {2}</span><h3>{0}</h3></a>' -f $_.Name, $_.Count, $pl
    }) -join "`n")

    if ($protected) { return }

    $body = '<header class="masthead"><h1>{0}</h1>' -f $dir
    $body += '<p class="subtitle">A collection: whole-of-{0} studies, plus a page for each book within it. Every HTML study also exists as .odt and .md alongside it.</p>' -f $dir
    $body += '<p class="meta"><a href="../index.html" style="color:var(--accent)">&larr; Study Library</a></p></header>'
    if ($own)     { $body += ('<h2 class="section">{0} {1} overview &amp; synthesis</h2><div class="grid two lead">{2}</div>' -f $dir, ([char]0x2014), $own) }
    if ($members) { $body += '<h2 class="section">Books</h2><div class="grid three">{0}</div>' -f $members }
    $body += '<footer><p>Auto-generated by <code>rebuild-index.command</code>. This is a collection page; each book nested inside <code>{0}/</code> keeps its own page and links back here.</p></footer>' -f $dir

    Write-Page $idx (Get-PageShell ("$dir " + [char]0x2014 + " Study Library") $body)
}

# ----- gather books & build --------------------------------------------------
Write-Host "Rebuilding library indexes in: $Root"
if ($Dry) { Write-Host ("(DRY RUN " + [char]0x2014 + " nothing will be written)") }
Write-Host ""

$bookRows = New-Object System.Collections.ArrayList   # Rank, Name, Count, Kind
$pending = New-Object System.Collections.ArrayList     # folders with material but no html yet

$topDirs = Sort-Ordinal (Get-ChildItem -LiteralPath $Root -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notlike '.*' })

foreach ($d in $topDirs) {
    $name = $d.Name
    if (Test-Collection $name) {
        Build-CollectionIndex $name
        $r = Get-Rank (Get-Norm $name)
        $members = (Get-MemberSubdirs $name).Count
        [void]$bookRows.Add([pscustomobject]@{ Rank = $r; Name = $name; Count = $members; Kind = 'collection' })
        continue
    }
    $n = Get-HtmlCount $name
    if ($n -eq 0) {
        $md = Get-ChildItem -LiteralPath $d.FullName -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Extension -eq '.md' -or $_.Extension -eq '.odt' }
        if (@($md).Count -gt 0) { [void]$pending.Add($name) }
        continue
    }
    $r = Get-Rank (Get-Norm $name)
    [void]$bookRows.Add([pscustomobject]@{ Rank = $r; Name = $name; Count = $n; Kind = 'book' })
    Build-BookIndex $name
}

# ----- top-level portal ------------------------------------------------------
$sorted = @($bookRows | Sort-Object Rank)

function Emit-Cards([string]$which) {
    $rows = $sorted | Where-Object {
        $rk = $_.Rank
        if     ($which -eq 'OT') { $rk -le 39 }
        elseif ($which -eq 'NT') { $rk -ge 40 -and $rk -le 66 }
        else                     { $rk -ge 900 }
    }
    return (($rows | ForEach-Object {
        if ($_.Kind -eq 'collection') {
            $pl = if ($_.Count -eq 1) { 'book' } else { 'books' }
        } else {
            $pl = if ($_.Count -eq 1) { 'document' } else { 'documents' }
        }
        '<a class="card" href="{0}/index.html"><span class="ref">{1} {2}</span><h3>{0}</h3></a>' -f $_.Name, $_.Count, $pl
    }) -join "`n")
}

$otCards = Emit-Cards 'OT'
$ntCards = Emit-Cards 'NT'
$otherCards = Emit-Cards 'OTHER'
$bookcount = $sorted.Count
$today = (Get-Date).ToString('d MMMM yyyy', [Globalization.CultureInfo]::GetCultureInfo('en-GB'))

$pbody = '<header class="masthead"><h1>Dig Deeper ' + [char]0x2014 + ' Study Library</h1>'
$pbody += '<p class="subtitle">A growing library of Bible-study material: whole-book overviews, cross-passage syntheses, and passage-by-passage exegetical reports.</p>'
$pbody += ('<p class="meta">Local catalogue &middot; {0} book(s) with HTML &middot; rebuilt {1}</p></header>' -f $bookcount, $today)

if (Test-Path -LiteralPath (Get-FsPath 'preaching-toolkit-guide.html')) {
    $pbody += '<div class="grid lead"><a class="card" href="preaching-toolkit-guide.html"><span class="ref big">Guide</span><h3>About the Preaching Toolkit</h3><p>How the overviews, sweeps, digs and syntheses fit together.</p></a></div>'
}

if ($otCards)    { $pbody += '<h2 class="section">Old Testament</h2><div class="grid three">{0}</div>' -f $otCards }
if ($ntCards)    { $pbody += '<h2 class="section">New Testament</h2><div class="grid three">{0}</div>' -f $ntCards }
if ($otherCards) { $pbody += '<h2 class="section">Other</h2><div class="grid three">{0}</div>' -f $otherCards }

$pfoot = '<footer><p>This is a local index. Every link is a file in this folder tree, so the whole library works offline &mdash; just open <code>index.html</code> and click through. Nothing is published online.</p>'
if ($pending.Count -gt 0) {
    $pfoot += '<p>Also in the library, not yet rendered to HTML: {0}.</p>' -f ($pending -join ', ')
}
$pfoot += '<p>To refresh this catalogue after adding material, double-click <code>rebuild-index.command</code>. Hand-made book pages are never overwritten.</p></footer>'
$pbody += $pfoot

Write-Page 'index.html' (Get-PageShell ('Dig Deeper ' + [char]0x2014 + ' Study Library') $pbody)

Write-Host ""
Write-Host "Done. Open  index.html  in your browser."
